version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: cieszk
      POSTGRES_PASSWORD: PiesKot69!
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db